//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizPansiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriEkle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriEkle()
        {
            this.odalar = new HashSet<odalar>();
        }
    
        public int musteriID { get; set; }
        public string musteriAdi { get; set; }
        public string musteriSoyadi { get; set; }
        public string musteriCinsiyet { get; set; }
        public string musteriTelefon { get; set; }
        public string musteriMail { get; set; }
        public string musteriTC { get; set; }
        public int ucret { get; set; }
        public System.DateTime girisTarihi { get; set; }
        public System.DateTime cikisTarihi { get; set; }
        public Nullable<int> odaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odalar> odalar { get; set; }
        public virtual odalar odalar1 { get; set; }
    }
}
