//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizPansiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class stoklar
    {
        public int urunID { get; set; }
        public Nullable<int> gida { get; set; }
        public Nullable<int> icecek { get; set; }
        public Nullable<int> cerez { get; set; }
    }
}
