//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizPansiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FaturaList
    {
        public int ID { get; set; }
        public Nullable<int> Elektrik { get; set; }
        public Nullable<int> Su { get; set; }
        public Nullable<int> İnternet { get; set; }
    }
}
