//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YildizPansiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MusteriList
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string TC_No { get; set; }
        public Nullable<int> Oda_No { get; set; }
        public int Ücret { get; set; }
        public System.DateTime Giriş_Tarihi { get; set; }
        public System.DateTime Çıkış_Tarihi { get; set; }
    }
}
